#!/usr/bin/env bash
# Recompute the SRI hashes for the TCA's pinned scripts and write them into the
# integrity= attributes of dvf.html / dvf_authorize.html.
#
# Stale hashes fail silently at the network layer (the browser just refuses the
# script), so this is run after every edit to tca/*.js — see tca/SRI.md.
#
#   ./tca/update-sri.sh            rewrite in place
#   ./tca/update-sri.sh --check    exit non-zero if any hash is stale
set -euo pipefail

cd "$(dirname "$0")"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

STALE=0
# Only the built bundles are referenced by the HTML, so only they are pinned.
# They are generated by build-app.sh (which in turn inlines cryptolib.js and
# vendor/crypto-deps.js); rebuild before running this script or the hash will
# pin the previous build. The sources are not fetched by the browser and need
# no hashes of their own.
for js in dvf.bundle.js dvf_authorize.bundle.js; do
    hash="sha384-$(openssl dgst -sha384 -binary "$js" | openssl base64 -A)"
    for html in dvf.html dvf_authorize.html; do
        grep -q "\./$js\"" "$html" || continue
        current=$(perl -0777 -ne "print \$1 if m{\Q./$js\E\"[^>]*?integrity=\"([^\"]*)\"}s" "$html")
        [ "$current" = "$hash" ] && continue

        STALE=1
        if [ "$CHECK" = "1" ]; then
            echo "STALE  $html: $js" >&2
            echo "       have $current" >&2
            echo "       want $hash" >&2
        else
            perl -0777 -pi -e "s{(\Q./$js\E\"[^>]*?integrity=\")[^\"]*(\")}{\${1}$hash\${2}}s" "$html"
            echo "updated $html: $js -> $hash"
        fi
    done
done

if [ "$CHECK" = "1" ] && [ "$STALE" = "1" ]; then
    echo "SRI hashes are stale — run ./tca/update-sri.sh" >&2
    exit 1
fi

[ "$STALE" = "0" ] && echo "all SRI hashes current"
exit 0
