// Browser-visible configuration: the window.ORION script served to pages and the
// CSP directive pinning the TCA iframe origin.
package config

import (
	"encoding/json"
	"fmt"
	"strings"
)

// PubConfigJS renders the browser-visible configuration as a classic script that
// assigns window.ORION, so served pages carry no compiled-in service addresses.
// It exposes service origins and the profile name only, which is why it can be
// served unauthenticated.
func (c *Config) PubConfigJS() string {
	pc := c.PublicConfig()

	enc := func(v string) string {
		b, err := json.Marshal(v)
		if err != nil {
			return `""`
		}
		return string(b)
	}

	origins := c.BrowserOrigins()
	quoted := make([]string, 0, len(origins))
	for _, o := range origins {
		quoted = append(quoted, enc(o))
	}

	return fmt.Sprintf(`// Generated by internal/config.PubConfigJS — do not edit.
// Public routing information for this deployment; contains no secrets.
window.ORION = {
  profile: %s,
  idpOrigin: %s,
  brokerOrigin: %s,
  rpOrigin: %s,
  tcaOrigin: %s,
  // Every origin in this deployment, including localhost/127.0.0.1 twins, for
  // inbound postMessage allow-lists. Outbound messages must still target one
  // exact origin.
  allowedOrigins: [%s]
};
`,
		enc(pc.Profile),
		enc(Origin(pc.IdP)),
		enc(Origin(pc.Broker)),
		enc(Origin(pc.RP)),
		enc(Origin(pc.TCA)),
		strings.Join(quoted, ", "),
	)
}

// FrameSrcCSP builds the frame-src directive permitting the TCA iframe and
// nothing else, covering both the configured TCA origin and its
// localhost/127.0.0.1 twin. It is served as a response header, which page content
// cannot influence.
func (c *Config) FrameSrcCSP() string {
	return "frame-src " + strings.Join(originAliases(c.TCA.Browser), " ")
}
